"""add tree_spacing_m and shrub_spacing_m to plans

Revision ID: a5e5d405366e
Revises: c40b39ca389b
Create Date: 2026-09-12 21:01:15.807558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e5d405366e'
down_revision: Union[str, Sequence[str], None] = 'c40b39ca389b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('tree_spacing_m', sa.Float(), nullable=True))
    op.add_column('plans', sa.Column('shrub_spacing_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'shrub_spacing_m')
    op.drop_column('plans', 'tree_spacing_m')
    # ### end Alembic commands ###
