"""baseline schema

Revision ID: c40b39ca389b
Revises: 
Create Date: 2026-09-11 20:31:33.977535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c40b39ca389b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    The two `op.create_index(...idx_*_geometry...)` calls autogenerate
    proposed here were removed by hand: geoalchemy2's `Geometry` column type
    defaults to `spatial_index=True`, which makes it create that same GIST
    index itself via an `after_create` DDL event the moment `create_table`
    runs (the same thing `Base.metadata.create_all()` already relied on
    before this migration existed) -- keeping autogenerate's copy too made
    `alembic upgrade head` fail with "relation already exists".
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_crs', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('geometry', Geometry(srid=0, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scoring_mode', sa.String(), nullable=False),
    sa.Column('planting_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('materialized', sa.Boolean(), nullable=False),
    sa.Column('has_manual_edits', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planting_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('geometry', Geometry(srid=0, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('planting_type', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('is_manual_edit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planting_items')
    op.drop_table('plans')
    op.drop_table('layers')
    op.drop_table('projects')
    # ### end Alembic commands ###
